name: Telegram Notification

on:
  pull_request:
    branches:
      - main
    types: [opened]  # Trigger only when a new PR is opened

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}  
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }} 
          message: |
            🚨 New Pull Request Opened on Main Branch 🚨

            *Title:* ${{ github.event.pull_request.title }}
            *Author:* ${{ github.event.pull_request.user.login }}
            *Source Branch:* ${{ github.event.pull_request.head.ref }} 
            *URL:* ${{ github.event.pull_request.html_url }}
            *Repository:* ${{ github.repository }}
