name: Telegram Notification

on:
  pull_request:
    branches:
      - main
    types: [opened, closed]

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job
        id: job_info
        run: echo "Job started"

      - name: Send Telegram Message for Opened PR
        if: github.event.action == 'opened'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ✅ *New Pull Request Opened* in _${{ github.repository }}_

            **Details:**
                **Title:** _${{ github.event.pull_request.title }}_
                **Author:** _${{ github.event.pull_request.user.login }}_
                **Source Branch:** _${{ github.event.pull_request.head.ref }}_
                **Link:** [View Pull Request](${{ github.event.pull_request.html_url }})

      - name: Send Telegram Message for Closed PR
        if: github.evt.action == 'closed'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            🚫 *Pull Request Closed* in _${{ github.repository }}_

            **Details:**
                **Title:** _${{ github.event.pull_request.title }}_
                **Author:** _${{ github.event.pull_request.user.login }}_
                **Source Branch:** _${{ github.event.pull_request.head.ref }}_
                **Merged:** _${{ github.event.pull_request.merged == true && 'Yes' || 'No' }}_
                **Link:** [View Pull Request](${{ github.event.pull_request.html_url }})
