name: Telegram Notification

on:
  pull_request:
    branches:
      - main
    types: [opened, closed]

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job
        id: job_info
        run: echo "Job started"

      - name: Send Telegram Message for Opened PR
        if: github.event.action == 'opened'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ✅ New Pull Request Opened in ${{ github.repository }}

            Title: ${{ github.event.pull_request.title }}
            Author: ${{ github.event.pull_request.user.login }}
            Source Branch: ${{ github.event.pull_request.head.ref }}
            Link: ${{ github.event.pull_request.html_url }}

      - name: Send Telegram Message for Closed PR
        if: github.event.action == 'closed'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            🚫 Pull Request Closed in ${{ github.repository }}

            Title: ${{ github.event.pull_request.title }}
            Author: ${{ github.event.pull_request.user.login }}
            Source Branch: ${{ github.event.pull_request.head.ref }}
            Merged: ${{ github.event.pull_request.merged == true && 'Yes' || 'No' }}
            Link: ${{ github.event.pull_request.html_url }}
