name: Telegram Notification

on:
  pull_request:
    branches:
      - main
    types: [opened, closed]

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}  
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }} 
          message: |
            ${{ github.event.action == 'opened' && '✅ New Pull Request Opened' || '🚫 Pull Request Closed' }} in *${{ github.repository }}*

            **Details:**
            - **Title:** ${{ github.event.pull_request.title }}
            - **Author:** ${{ github.event.pull_request.user.login }}
            - **Source Branch:** ${{ github.event.pull_request.head.ref }}
            - ${{ github.event.action == 'closed' && '*Merged:* ' + github.event.pull_request.merged || '' }}
            - **Link:** ${{ github.event.pull_request.html_url }}